Feature/component
er-nick-cr/TouchCar pull request #12
Opened 2022-07-03 09:33 UTC by er-nick-cr

2022-07-04 13:18 UTC, Perfomer requested changes

2022-07-04 13:18 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/component/ComponentImageView.kt
> +    var centreY = 0f
private

2022-07-04 13:18 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/component/ComponentImageView.kt
> +    lateinit var onClickImage: (SelectedCoordinates) -> Unit
no lateinit pls

2022-07-04 13:18 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/component/ComponentImageView.kt
> +    private val scaleListener = object : ScaleGestureDetector.SimpleOnScaleGestureListener() {
лучше убрать логику из списка полей

2022-07-04 13:18 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/component/ComponentImageView.kt
> +            return true
можно объединить в один иф + точку с запятой убрать)

2022-07-04 13:18 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/component/ComponentImageView.kt
> +                    onClickImage.invoke(selectedCoordinates)
ретурн фолс

2022-07-04 13:18 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/component/ComponentImageView.kt
> +        override fun onSingleTapConfirmed(event: MotionEvent?): Boolean {
event is never null

2022-07-04 13:18 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/component/ComponentImageView.kt
> +    override fun onDraw(canvas: Canvas?) {
canvas can't be null

2022-07-04 13:18 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/component/ComponentImageView.kt
> +        return super.onDragEvent(event)
ne nado()

2022-07-04 13:18 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/component/ComponentViewModel.kt
> +    fun convertCoordinates(
лучше убрать в кастомвью

2022-07-04 13:18 UTC, Perfomer commented on feature-parts/src/main/res/layout/component_fragment.xml
> +        android:layout_marginTop="6dp"
маргинтоп 18дп

2022-07-04 13:18 UTC, Perfomer commented on feature-parts/src/main/res/layout/component_fragment.xml
> +        android:layout_marginTop="55dp"
?

2022-07-04 13:18 UTC, Perfomer commented on feature-parts/src/main/res/layout/component_recycler_item.xml
> +        app:layout_constraintEnd_toStartOf="@id/next"
24

2022-07-04 13:18 UTC, Perfomer commented on feature-parts/src/main/res/layout/component_recycler_item.xml
> +        android:contentDescription="@string/next" />
suppress, clean string resources

2022-07-09 13:37 UTC, Perfomer requested changes

2022-07-09 13:37 UTC, Perfomer commented on core-common/src/main/java/com/example/core_common/BaseListItem.kt
> +class ListItem<T>(override val id: String, val item: T) : BaseListItem
Этот класс можно убрать внутрь `BaseAdapter` класса и сделать его приватным, так как за его пределами он нигде не используется.

2022-07-09 13:37 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/component/ComponentFragment.kt
> +                    context?.let { convertPxToDp(it, BOTTOM_SHEET_HEIGHT) }!!
ну в целом логично: сначала проверяем на нулл `context?.let`, а потом "ЭТО НЕ НУЛЛ`!!`!!!11111"
здесь контекст не может быть нулл, используй вместо `context` функцию `requireContext()`

2022-07-09 13:37 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/component/ComponentFragment.kt
>      }
Этому не место здесь. Лучше в коммоны унести

2022-07-09 13:37 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/widget/component/ComponentImageView.kt
> +) : androidx.appcompat.widget.AppCompatImageView(context, attrs, defStyle) {
А почему без импорта родительский класс? о_О

2022-07-09 13:37 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/widget/component/ComponentImageView.kt
> +class ComponentImageView @JvmOverloads constructor(
internal?

2022-07-09 13:37 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/widget/component/ComponentImageView.kt
> +    var image: Bitmap? = null
Эти два поля точно паблик должны быть?

2022-07-09 13:37 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/widget/component/ComponentImageView.kt
> +                centreX = ((width - image!!.width) / 2).toFloat()
> `centre`

о, вы из британии))

2022-07-09 13:37 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/widget/component/ComponentImageView.kt
> +                color = ContextCompat.getColor(context, R.color.component_item_stroke)
сделай свою утилитную функцию экстеншен в стиле котлина
`context.getColorCompat(R.color.component_item_stroke)`

2022-07-09 13:37 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/widget/component/ComponentImageView.kt
> +        GlideApp.with(this)
Много лишнего кода. Давай тоже в экстеншен вынесем, чтобы было как-то так:
```kotlin
context.loadImage(
    imageUrl = url,
    onSuccess = { bitmap: Bitmap -> onImageLoaded(bitmap) },
    onFailure = { error: Throwable -> e.printStackTrace() },
)
```

2022-07-10 04:58 UTC, Perfomer commented on feature-parts/src/main/java/com/example/feature_parts/component/ComponentFragment.kt
>      }
#4 пункт
https://medium.com/codex/extension-functions-you-need-to-know-in-android-a87c2e9b5d9e

2022-07-10 10:52 UTC, er-nick-cr commented on feature-parts/src/main/java/com/example/feature_parts/widget/component/ComponentImageView.kt
> +                centreX = ((width - image!!.width) / 2).toFloat()
ахахахахахахахаха

2022-07-10 13:32 UTC, Perfomer commented on core-common/src/main/java/com/example/core_common/TouchCarGlideModule.kt
> +}
Тело класса можно не писать, если оно пустое.

2022-07-10 13:33 UTC, Perfomer commented on core-common/src/main/java/com/example/core_common/utils/GetColorUtils.kt
> +
Пропуск строки зачем?

2022-07-10 13:50 UTC, merged