Feature/progress bar
er-nick-cr/TouchCar pull request #21
Opened 2022-08-26 07:43 UTC by er-nick-cr

2022-08-26 09:54 UTC, Perfomer requested changes

2022-08-26 09:54 UTC, Perfomer commented on feature-car-search/src/main/java/com/example/feature_car_search/presentation/choose_body/ChooseBodyViewModel.kt
> +                        isLoadingLiveData.postValue(false)
В случае ошибки будет вечный прогрессбар?

2022-08-26 09:54 UTC, Perfomer commented on feature-main-menu/src/main/java/com/example/feature_main_menu/main_menu/search_by_vin_bottom_sheet/SearchByVinBottomSheetFragment.kt
> +                detailedPartButton.setBackgroundColor(requireContext().getColor(R.color.disabled_color))
А обратно раздуплять цвет кнопки если загрузка прервана, например ошибкой?

2022-08-30 14:45 UTC, er-nick-cr commented on feature-main-menu/src/main/java/com/example/feature_main_menu/main_menu/search_by_vin_bottom_sheet/SearchByVinBottomSheetFragment.kt
> +                detailedPartButton.setBackgroundColor(requireContext().getColor(R.color.disabled_color))
Соре

2022-08-30 16:10 UTC, Perfomer requested changes

2022-08-30 16:10 UTC, Perfomer commented on feature-car-search/src/main/res/layout/choose_body_fragment.xml
> +        android:theme="@style/CircularProgress"
Он же и так должен брать `accentColor`? Зачем это?

2022-08-30 16:10 UTC, Perfomer commented on feature-main-menu/src/main/res/layout/main_menu_manufacturer_recycler_item.xml
>      android:layout_marginBottom="10dp"
marginStart + marginEnd = marginHorizontal
marginTop + marginBottom = marginVertical

2022-08-30 16:12 UTC, Perfomer commented on feature-car-search/src/main/java/com/example/feature_car_search/presentation/choose_body/ChooseBodyViewModel.kt
> +                        isLoadingLiveData.postValue(false)
Чтобы не писать окончание загрузки как в `onSuccess`, так и в `onError`, можно использовать такое в цепочке:
`.doAfterTerminate { isLoadingLiveData.postValue(false) }`

2022-08-30 16:15 UTC, Perfomer commented on feature-main-menu/src/main/java/com/example/feature_main_menu/main_menu/search_by_vin_bottom_sheet/SearchByVinBottomSheetFragment.kt
> +                    detailedPartButton.setBackgroundColor(requireContext().getColor(R.color.disabled_color))
А как же раздупление фона кнопки при окончании загрузки?

2022-08-30 16:19 UTC, Perfomer commented on feature-main-menu/src/main/res/layout/main_menu_fragment.xml
> +            android:foreground="?selectableItemBackground"
Ого, а чё у кнопки без этого атрибута нет риппла?

2022-08-31 13:07 UTC, er-nick-cr commented on feature-main-menu/src/main/java/com/example/feature_main_menu/main_menu/search_by_vin_bottom_sheet/SearchByVinBottomSheetFragment.kt
> +                    detailedPartButton.setBackgroundColor(requireContext().getColor(R.color.disabled_color))
соре х2

2022-09-01 12:27 UTC, Perfomer approved these changes

2022-09-02 12:43 UTC, merged